export enum textTypes{
    TITLE_BOLD = 'TITLE_BOLD',
    TITLE_REGULAR = 'TITLE_REGULAR',
    TITLE_LIGHT = 'TITLE_LIGHT',
    SUBTITLE_BOLD = "SUBTITLE_BOLD",
    SUBTITLE_REGULAR = "SUBTITLE_REGULAR",
    SUBTITLE_LIGHT = "SUBTITLE_LIGHT",
    PARAGRAPH_BOLD = 'TITLE_BOLD',
    PARAGRAPH_REGULAR = 'TITLE_REGULAR',
    PARAGRAPH_LIGHT = 'TITLE_LIGHT',
    BUTTON_BOLD = 'BUTTON_BOLD',
    BUTTON_MEDIUM = 'BUTTON_MEDIUM',
    BUTTON_LIGHT = 'BUTTON_LIGHT'
}